# Generated by Django 4.1.3 on 2022-12-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_familia_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='fecha',
        ),
    ]
