# Generated by Django 4.1.3 on 2022-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_familia_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte_favorito', models.CharField(max_length=40)),
                ('club', models.CharField(max_length=40)),
                ('posicion', models.CharField(max_length=40)),
                ('años_jugando', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('barrio', models.CharField(max_length=40)),
                ('codigo_postal', models.IntegerField()),
            ],
        ),
    ]
